name: Run Python Script

on:
  push:               
    branches: [ "*" ] 

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # You can change the version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # pip install -r requirements.txt  # Uncomment if needed

      - name: Run python.py
        run: python python.py
